<?php

namespace App\Http\Controllers\Api\Seller;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Resources\Seller\SellerTransactionResource;
use App\Models\Ecommerce\UserSellerTransaction;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class SellerTransactionController extends Controller
{
    /**
     * List transactions for the authenticated seller
     */
    public function index(Request $request): AnonymousResourceCollection
    {
        $transactions = UserSellerTransaction::where('user_id', $request->user()->id)
            ->latest()
            ->paginate(20);

        return SellerTransactionResource::collection($transactions)->additional(['success' => true]);
    }

    // Note: No update, destroy, or store methods are exposed here
    // to preserve the append-only nature of the ledger.
    // Transactions should be generated by the system during orders/withdrawals.
}
